modLoader = "javafml" #mandatory
loaderVersion = "[35,)" #mandatory (28 is current forge version)
issueTrackerURL = "http://my.issue.tracker/" #optional

license = "GNU Lesser General Public License v3.0"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId = "ars_oscura" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Ars Oscura" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
credits = "" #optional
authors = "mystchonky" #optional
description = '''
Ars Nouveau tainted by Dark Arts
'''

[[dependencies.ars_oscura]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[47.0,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.ars_oscura]]

modId = "patchouli"
mandatory = true
versionRange = "[1.20.1-81,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ars_oscura]]
modId = "curios"
mandatory = true
versionRange = "[1.18.1-5.0.3.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ars_oscura]]
modId = "ars_nouveau"
mandatory = true
versionRange = "[4.2.0,)"
ordering = "AFTER"
side = "BOTH"
